language: go
go:
- 1.4
- 1.5
- release
before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
- $HOME/gopath/bin/goveralls -service=travis-ci
- go vet ./...
- go test -i -race ./...
- go test -v -race ./...
- go test -v -bench=.